---
- hosts: all
  remote_user: root
  gather_facts: no
  pre_tasks:
    - raw: apt-get -y install python-simplejson || true
    - raw: yum -y install python-simplejson libselinux-python || true
    - raw: pacman -Sy --noconfirm python2 || true
  tasks:
    - name: create "{{ user }}" user
      user:
       name: "{{ user }}"
       shell: /bin/bash
       password: "{{ password_hash }}"
       state: present

    - name: add "{{ user }}" user to sudo group
      user:
        name: "{{ user }}"
        groups: sudo
        append: yes
      ignore_errors: yes

    - name: add "{{ user }}" user to wheel group
      user:
        name: "{{ user }}"
        groups: wheel
        append: yes
      ignore_errors: yes

    - name: set up authorized keys
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
